language: node_js
os :
  - windows
arch:
  - amd64
node_js:
  - 16
  - 15
  - 14
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
before-script:
  - yarn match-mocha-version
script :
  - yarn test
  - echo asd
branches:
  only:
    - master