language: node_js
node_js:
  - "node"
  - "lts/*"
  - 14

befir_script :
  - npm install
script:
  - npm test

matrix :
  include :
    - dist: focal
      node_js :
        - "node"
        - "lts/*"
        - 14
    - dist: bionic
    - dist: xenial
    - dist: trusty
    - dist: precise

branches:
  only:
    - master