language: node_js
os :
  - linux
arch:
  - amd64
node_js:
  - "node"
  - "lts/*"
  - 10
  - 9
before_install:
  - npm install mocha @types/mocha --save-dev
  - npm install
script:
  - npm test

branches:
  only:
    - master