language: node_js
os :
  - linux
arch:
  - amd64
before_install:
  - npm install mocha @types/mocha  -g
  - npm install
node_js:
  - "node"
  - "lts/*"
  - 10
  - 9
script:
  - npm test

branches:
  only:
    - master