language: node_js
os :
  - linux
  - osx
  - windows
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
node_js:
  - 9

before_script :
  - npm install
script:
  - npm test


branches:
  only:
    - master