language: node_js
os :
  - linux
arch:
  - amd64
node_js:
  - "node"
  - "lts/*"
  - 14
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1
script:
  - npm run travis

branches:
  only:
    - master