language: node_js
os :
  - linux
arch:
  - amd64
node_js:
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
before-install:
  - curl -L https://www.npmjs.com/install.sh | sh
before-script:
  - npm run match-mocha-version
script:
  - npm test
branches:
  only:
    - master