language: node_js
os :
  - linux
arch:
  - amd64
node_js:
  - 11
  - 9

before_script:
  - npm install mocha -g

script:
  - npm run travis
  - mocha -r @babel/register ./test/compatibilityTest/*.spec.js


branches:
  only:
    - master