language: node_js
node_js:
  - "node"
  - "lts/*"
  - 14

dist:
  - focal
  - bionic
  - xenial
  - trusty
  - precise

befir_script :
  - npm install
script:
  - npm test

branches:
  only:
    - master