language: node_js
os :
  - linux
  - osx
  - windows
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
node_js:
  - "node"
  - "lts/*"
  - 16
  - 15
  - 14
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
before-install:
  - npm install yarn -g
install:
  - yarn
before-script:
  - yarn match-mocha-version
script:
  - yarn test
branches:
  only:
    - master