language: node_js
os :
  - linux
arch:
  - amd64
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
install:
  - npm install
before-script:
  - npm run match-mocha-version
script:
  - npm test
branches:
  only:
    - master