language: node_js
os :
  - linux
arch:
  - amd64
node_js:
  - "node"
  - "lts/*"
  - 16
  - 15
  - 14
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
before-install:
  - npm install -g npm
install:
  - npm install
before-script:
  - npm run match-mocha-version
script:
  - npm test
branches:
  only:
    - master