language: node_js
os :
  - linux
arch:
  - amd64
node_js:
  - "node"
  - "lts/*"
  - 10
  - 9
install:
  - npm install
before-script:
  - npm run set-tf
script:
  - npm test

branches:
  only:
    - master