language: node_js
os :
  - linux
  - osx
  - windows
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
node_js:
  - 11
  - 10
  - 9
  - 8

before_script :
  - npm install
script:
  - npm run travis


branches:
  only:
    - master