version: '3.8'

services:
  workspace:
    container_name: koconut_devContainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: 16
        NPM_VERSION: 9.1.1

    volumes:
      - ..:/workspace:cached
      - koconut-node_modules:/workspace/node_modules

    command: sleep infinity
    ports:
      - 5000:5000
    user: node

volumes:
  koconut-node_modules:
