name: Node.js Conditional Unit Test CI

on:
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest] # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
        node-version: [7.x, 8.x, 11.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Match Test Inst Env
        run: npm install mocha@^6.x chai --production
      - name: Launch Coverage Test
        run: npm run test@coverage
