name: Node.js Conditional Unit Test CI

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 6.x ]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Runtime Dependencies
      run: npm install ts-node @types/node typescript --save-dev && npm run match-mocha-version

    - name: Install Rest Dependencies
      run: npm install 

    - name: Initiate Test
      run: npm doc@view