name: Manual CI

on:
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest] # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
        node-version: [7.x, 8.x, 9.x, 10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Production Dependency
        run: npm install --production
      - name: Install Test Inst Env
        run: npm install -g mocha chai
      - name: Launch Coverage Test
        run: npm run test@coverage
